-- Common Schemas..
/*Schema for Vertex*/
CREATE TABLE IF NOT EXISTS VERTEX (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(50) DEFAULT NULL,
	`NE_NAME` varchar(50) DEFAULT NULL,
	`VENDOR` varchar(50) DEFAULT NULL,
	`OWN_SP_DEC` varchar(100) DEFAULT NULL,
	`OWN_GT` text DEFAULT NULL,
	`OWN_MSRN` text DEFAULT NULL,
	`IP` varchar(400) DEFAULT NULL

)Engine=InnoDB;

-- Raw Schemas..
/*Schema for KAI*/
CREATE TABLE  IF NOT EXISTS KAI (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`SOURCE_ID` varchar(100) DEFAULT '',
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(200) DEFAULT NULL,
	`LINE` Integer(20) DEFAULT 0,
	`COMMAND_PARAM` varchar(100) DEFAULT NULL,
	`UNIT` VARCHAR(101),
	`APP_ID` VARCHAR(101),
	`IPV4` VARCHAR(101),
	`IPV6` VARCHAR(101)
)Engine=InnoDB;
/*Schema for EJH*/
CREATE TABLE  IF NOT EXISTS EJH (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`SOURCE_ID` varchar(100) DEFAULT '',
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(200) DEFAULT NULL,
	`LINE` Integer(20) DEFAULT 0,
	`COMMAND_PARAM` varchar(100) DEFAULT NULL,
	`PARAMETER` VARCHAR(101),
	`PARAM_SHORT` VARCHAR(101),
	`PARAM_VALUE` VARCHAR(101)
)Engine=InnoDB;
/*Schema for E6I*/
CREATE TABLE  IF NOT EXISTS E6I (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`SOURCE_ID` varchar(100) DEFAULT '',
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(200) DEFAULT NULL,
	`LINE` Integer(20) DEFAULT 0,
	`COMMAND_PARAM` varchar(100) DEFAULT NULL,
	`MCC` VARCHAR(103),
	`MNC` VARCHAR(102),
	`RNCID` VARCHAR(105),
	`RNCNAME` VARCHAR(101),
	`STATE` VARCHAR(101),
	`OPSTATE` VARCHAR(101),
	`PSET` VARCHAR(101),
	`PNAME` VARCHAR(101),
	`PGI` VARCHAR(101),
	`PAPU` VARCHAR(101),
	`DIG` VARCHAR(101),
	`NP` VARCHAR(101),
	`TON` VARCHAR(101),
	`NI` VARCHAR(101),
	`SPC` VARCHAR(101),
	`LAC` VARCHAR(105),
	`RAC` VARCHAR(103)
)Engine=InnoDB;
/*Schema for KAO*/
CREATE TABLE  IF NOT EXISTS KAO (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`SOURCE_ID` varchar(100) DEFAULT '',
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(200) DEFAULT NULL,
	`LINE` Integer(20) DEFAULT 0,
	`COMMAND_PARAM` varchar(100) DEFAULT NULL,
	`GBU` VARCHAR(101),
	`PAPU` VARCHAR(101)
)Engine=InnoDB;
/*Schema for ZWVI*/
CREATE TABLE  IF NOT EXISTS ZWVI (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`SOURCE_ID` varchar(100) DEFAULT '',
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(200) DEFAULT NULL,
	`LINE` Integer(20) DEFAULT 0,
	`COMMAND_PARAM` varchar(100) DEFAULT NULL,
	`NUMBER` VARCHAR(112),
	`NP` VARCHAR(101),
	`TON` VARCHAR(101),
	`TYPE` VARCHAR(101),
	`MOBILE_COUNTRY_CODE` VARCHAR(103),
	`MOBILE_NETWORK_CODE` VARCHAR(102),
	`PLMN_DEFAULT_CHARGING_AREA` VARCHAR(101),
	`CORE_NETWORK_NODE_IDTFR` VARCHAR(101)
)Engine=InnoDB;
/*Schema for ZB6O*/
CREATE TABLE  IF NOT EXISTS ZB6O (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`SOURCE_ID` varchar(100) DEFAULT '',
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(200) DEFAULT NULL,
	`LINE` Integer(20) DEFAULT 0,
	`COMMAND_PARAM` varchar(100) DEFAULT NULL,
	`TAI_MCC` VARCHAR(103),
	`TAI_MNC` VARCHAR(102),
	`TAI_TACS` VARCHAR(104),
	`LAI_MCC` VARCHAR(103),
	`LAI_MNC` VARCHAR(102),
	`LAI_LAC` VARCHAR(104),
	`VLRS` VARCHAR(101)
)Engine=InnoDB;
/*Schema for ZEJL*/
CREATE TABLE  IF NOT EXISTS ZEJL (
	`ENTRY_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	`SOURCE_ID` varchar(100) DEFAULT '',
	`DATETIME_ID` datetime NULL DEFAULT '0000-00-00 00:00:00',
	`NE_ID` varchar(200) DEFAULT NULL,
	`LINE` Integer(20) DEFAULT 0,
	`COMMAND_PARAM` varchar(100) DEFAULT NULL,
	`CI` VARCHAR(105),
	`BVCI` VARCHAR(105),
	`STATE` VARCHAR(101),
	`NSEI` VARCHAR(105),
	`PAPU` VARCHAR(101),
	`MCC` VARCHAR(103),
	`MNC` VARCHAR(102),
	`LAC` VARCHAR(105),
	`RAC` VARCHAR(103)
)Engine=InnoDB;
